### ISSUE TITLE
A query regarding EIP

### ISSUE THREAD

**Issue by ggoel1998** [6mxo89sqh/covid-vaccine-booking#2]
Hey , I am new to AWS , so I had a query whether I have to assign region as India when allocating EIP because I think Cowin api is restricted by region

**Comment by 6mxo89sqh** [comment]
Yes, you need to assign in `ap-south-1` region.

**Comment by ggoel1998** [comment]
@6mxo89sqh  how do i connect to private IP of the instance assigned with EIP

**Comment by 6mxo89sqh** [comment]
You need to boot one more instance and connect from there or assign one more EIP (secondary).

**Comment by ggoel1998** [comment]
I have booted up secondary instance, but confused how to connect to primary instance being a newbie to aws
Thanks a ton if you could describe the steps

**Comment by 6mxo89sqh** [comment]
Get the Private IP of primary machine from ec2 console and public IP of secondary machine from ec2 console.

1. Add your key `ssh-add <<key_file_path>>` 
2. Connect to secondary machine`ssh -i <key_file_path> <machine-user>@<machine_public_ip>`
3. Connect to primary machine `ssh <machine-user>@<private ip of primary machine>`

**Comment by 6mxo89sqh** [comment]
@ggoel1998 worked?

**Comment by darthfishious** [comment]
after creating elastic id, does it have to be associated with the primary instance?

**Comment by 6mxo89sqh** [comment]
Yes

**Comment by shivaslifzz** [comment]
@6mxo89sqh thanks bro finally able to over come the rate limit issue 

![image](https://user-images.githubusercontent.com/61616987/120831935-b6990e80-c57d-11eb-91e8-b126bf88f8b6.png)
![image](https://user-images.githubusercontent.com/61616987/120833194-20fe7e80-c57f-11eb-8fa6-fcadadc9a93b.png)

**Comment by ggoel1998** [comment]
@6mxo89sqh Hey thanks alot , it's working now .
Also , Do we have to perform these steps everytime whenever I want to open up to check ec2 instance or can I just directly ssh into secondary instance now?

**Comment by 6mxo89sqh** [comment]
directly ssh to second instance now :)

**Comment by ggoel1998** [comment]
Thanks alot buddy , you are a lifesaver @6mxo89sqh 
Stay safe !
