### ISSUE TITLE
The COWIN restricition

### ISSUE THREAD

**Issue by KUSHAGRA211** [6mxo89sqh/covid-vaccine-booking#3]
The same problem with COWIN restriction persists. after 20 searches

**Comment by 6mxo89sqh** [comment]
Which branch are you trying?

**Comment by saurabh1069** [comment]
still not working
![image](https://user-images.githubusercontent.com/26090183/120712914-ddecce80-c4de-11eb-88c0-1ee7b6e7bc94.png)

**Comment by saurabh1069** [comment]
which branch to try..?

**Comment by saurabh1069** [comment]
doing something wrong i sense...

**Comment by 6mxo89sqh** [comment]
> which branch to try..?
> 

rate-count-fix

**Comment by saurabh1069** [comment]
yes tried this one only...its just not working. you can see snap i have attached, does it worked for you..?

**Comment by KUSHAGRA211** [comment]
@6mxo89sqh Tried on your rate-count-fix branch and got this 
![image](https://user-images.githubusercontent.com/50497135/120749937-11e9e300-c523-11eb-97ac-535af51909f7.png)

**Comment by saurabh1069** [comment]
Are you Trying in  Ec2 or docker can't see any Ip reassignment logic kicking in.

**Comment by KUSHAGRA211** [comment]
@saurabh1069 Whenever run this command from the instructuion it return this 
![image](https://user-images.githubusercontent.com/50497135/120752298-1a441d00-c527-11eb-8a94-7a51f779d5e3.png)

**Comment by 6mxo89sqh** [comment]
@KUSHAGRA211 can you share what is your setup?

**Comment by KUSHAGRA211** [comment]
> @KUSHAGRA211 can you share what is your setup?

Oky So after reading your edit on bombardier #452 about  "Not using it along with 7 day" Now it is owkring fine on my computer. :) Thanks, But it is not getting setup in AWS. I am a newbie :(

**Comment by 6mxo89sqh** [comment]
Awesome

**Comment by jeethjoseph** [comment]
How do we use IP reassignment?
How do we use single day search instead of seven day search?
